repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.4
      hooks:
          - id: ruff
            name: ruff (lint)
            stages: [push]
            args: ["--fix", "--exit-non-zero-on-fix"]
          - id: ruff-format
            name: ruff (format)
            stages: [push]
    - repo: https://github.com/psf/black
      rev: 24.4.2
      hooks:
          - id: black
            language_version: python3.11
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            additional_dependencies: [types-requests]
            language_version: python3.11
    - repo: local
      hooks:
          - id: pytest
            name: pytest (unit + lint)
            entry: uv run pytest -m "not integration"
            language: system
            pass_filenames: false
