# Data Configuration for EUR/USD Trading

# Currency Pair
instrument: "EUR/USD"

# Timeframes to support
timeframes:
    - "5m"
    - "15m"
    - "1h"
    - "4h"
    - "1d"

# Historical Data Configuration
historical:
    start_date: "2003-01-01" # 21 years of data
    end_date: "2024-01-01"
    primary_timeframe: "1h" # Main timeframe for training

# Data Sources
sources:
    # forex.com API
    forex_com:
        enabled: true
        api_key: ${FOREX_COM_API_KEY}
        api_secret: ${FOREX_COM_API_SECRET}
        base_url: "https://api.forex.com"
        rate_limit: 100 # requests per minute

    # Alpaca API
    alpaca:
        enabled: true
        api_key: ${ALPACA_API_KEY}
        api_secret: ${ALPACA_API_SECRET}
        base_url: "https://paper-api.alpaca.markets" # Use paper trading initially
        rate_limit: 200 # requests per minute

    # Alpha Vantage for historical data
    alpha_vantage:
        enabled: true
        api_key: ${ALPHA_VANTAGE_API_KEY}
        base_url: "https://www.alphavantage.co"
        rate_limit: 5 # requests per minute (free tier)

    # Yahoo Finance as backup
    yahoo_finance:
        enabled: true
        symbol: "EURUSD=X"
        rate_limit: 2000 # requests per hour

# Data Quality
quality_checks:
    max_missing_ratio: 0.05 # 5% maximum missing data
    min_data_points: 1000
    outlier_detection: true
    duplicate_removal: true

# Storage Configuration
storage:
    raw_data_path: "./data/raw"
    processed_data_path: "./data/processed"
    qlib_data_path: "./data/qlib_format"
    cache_enabled: true
    cache_ttl: 3600 # seconds
