# Qlib Configuration

# Qlib Initialization
qlib_init:
    provider_uri: "./data/qlib_format" # Local data storage
    region: "custom" # Custom region for forex data

# Data Provider Configuration
data_provider:
    calendar_provider: "LocalCalendarProvider"
    instrument_provider: "LocalInstrumentProvider"
    feature_provider: "LocalFeatureProvider"
    expression_provider: "LocalExpressionProvider"
    dataset_provider: "LocalDatasetProvider"

# Market Configuration
market:
    trading_calendar: "custom_forex" # 24/5 forex calendar
    instruments: ["EURUSD"] # Single instrument for now

# Dataset Configuration
dataset:
    class: "DatasetH"
    kwargs:
        handler:
            class: "Alpha158" # Will be customized for forex
            kwargs:
                start_time: "2003-01-01"
                end_time: "2024-01-01"
                fit_start_time: "2003-01-01"
                fit_end_time: "2020-12-31"
                instruments: ["EURUSD"]
                infer_processors:
                    - class: "RobustZScoreNorm"
                      kwargs:
                          fields_group: "feature"
                          clip_outlier: true
                    - class: "Fillna"
                      kwargs:
                          fields_group: "feature"
                learn_processors:
                    - class: "DropnaLabel"
                    - class: "CSRankNorm"
                      kwargs:
                          fields_group: "label"
        segments:
            train: ["2003-01-01", "2020-12-31"]
            valid: ["2021-01-01", "2022-12-31"]
            test: ["2023-01-01", "2024-01-01"]

# Model Configuration Template
model_template:
    class: "LGBModel" # Default model (will be replaced by RL models)
    kwargs:
        loss: "mse"
        colsample_bytree: 0.8879
        learning_rate: 0.0421
        subsample: 0.8789
        lambda_l1: 205.6999
        lambda_l2: 580.9768
        max_depth: 8
        num_leaves: 210
        num_threads: 20

# Backtest Configuration
backtest:
    strategy:
        class: "TopkDropoutStrategy"
        kwargs:
            signal: "score"
            topk: 1
            n_drop: 0
    backtest:
        start_time: "2023-01-01"
        end_time: "2024-01-01"
        account: 100000
        benchmark: "SH000905"
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: "close"
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5

# Cache Configuration
cache:
    mem_cache_size: "5GB"
    redis_host: "localhost"
    redis_port: 6379
    redis_db: 0
    enable_redis: false # Disable Redis initially
