import { z } from "zod";

const ValidationError = z
	.object({
		loc: z.array(z.union([z.string(), z.number()])),
		msg: z.string(),
		type: z.string(),
	})
	.passthrough();
const HTTPValidationError = z
	.object({ detail: z.array(ValidationError) })
	.partial()
	.passthrough();
const ExperimentLaunchRequest = z
	.object({
		agent_type: z.string().default("ppo"),
		symbol: z.string().default("EUR/USD"),
		timeframe: z.string().default("1h"),
		timesteps: z.number().int().gte(1000).default(50000),
		learning_rate: z.number().gt(0).default(0.0003),
		initial_balance: z.number().gt(0).default(10000),
	})
	.partial()
	.passthrough();
const ExperimentLaunchResponse = z
	.object({ experiment_id: z.string(), status: z.string() })
	.passthrough();

export const schemas = {
	ValidationError,
	HTTPValidationError,
	ExperimentLaunchRequest,
	ExperimentLaunchResponse,
};

// Note: This file was generated by openapi-zod-client but Zodios is not available
// For now, we'll export just the schemas until Zodios is added as a dependency

// Placeholder API client - replace with actual implementation when Zodios is available
export const api = {
	list_experiments_experiments_get: async (params?: { limit?: number }) => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
	launch_experiment_experiments_post: async (
		body: z.infer<typeof ExperimentLaunchRequest>
	) => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
	experiment_detail_experiments__experiment_id__get: async (
		experiment_id: string
	) => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
	stop_experiment_experiments__experiment_id__stop_post: async (
		experiment_id: string
	) => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
	experiments_summary_experiments_summary_get: async () => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
	health_health_get: async () => {
		throw new Error(
			"API client not implemented - Zodios dependency missing"
		);
	},
};

export function createApiClient(
	baseUrl: string,
	options?: Record<string, unknown>
) {
	throw new Error(
		"createApiClient not implemented - Zodios dependency missing"
	);
}
